/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasbesarkelompok2.View;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import tugasbesarkelompok2.koneksi.koneksi;

/**
 *
 * @author User
 */
public class LoginRegister extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;

    
    public LoginRegister() {
        initComponents();
        koneksi db = new koneksi();
        db.config();
        con = db.con;
        stat = db.stm;
    }
    /**
     * Creates new form LoginRegister
     */
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        btnCreate = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JPanel();
        bt_login = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        Register = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jPasswordField4 = new javax.swing.JPasswordField();
        haveAccount = new javax.swing.JLabel();
        btnRegCreate = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        background2 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        listMenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnTambahData = new javax.swing.JLabel();
        btnJualBarang = new javax.swing.JLabel();
        btnCekstok = new javax.swing.JLabel();
        btnAbout = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        btnHistoriPenjualan = new javax.swing.JLabel();
        panelWelcome = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        panelTambahData = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtTambahKode = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtTambahNamaBarang = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtTambahTipe = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtTambahHarga = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtTambahJumlah = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTambahKeterangan = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        panelJualBarang = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtJualTanggal = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtJualBarang = new javax.swing.JTextField();
        txtJualNamaPembeli = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtJualTipe = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtJualKode = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        txtJualJumlah = new javax.swing.JTextField();
        panelCekStok = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelHistori = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        panelAbout = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("HELLO");
        Login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/password.png"))); // NOI18N
        Login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/username.png"))); // NOI18N
        Login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        txt_name.setBackground(new java.awt.Color(0, 0, 0, 50));
        txt_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_name.setForeground(new java.awt.Color(204, 255, 255));
        Login.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 170, -1));

        txt_pass.setBackground(new java.awt.Color(0, 0, 0, 50));
        txt_pass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_pass.setForeground(new java.awt.Color(204, 255, 255));
        txt_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_passMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_passMouseEntered(evt);
            }
        });
        Login.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 170, -1));

        btnCreate.setBackground(new java.awt.Color(153, 153, 153));
        btnCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCreateMouseExited(evt);
            }
        });

        jLabel4.setText("CREATE");

        javax.swing.GroupLayout btnCreateLayout = new javax.swing.GroupLayout(btnCreate);
        btnCreate.setLayout(btnCreateLayout);
        btnCreateLayout.setHorizontalGroup(
            btnCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(btnCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnCreateLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnCreateLayout.setVerticalGroup(
            btnCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(btnCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnCreateLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Login.add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 70, 30));

        btnLogin.setBackground(new java.awt.Color(153, 153, 153));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });

        bt_login.setText("LOGIN");

        javax.swing.GroupLayout btnLoginLayout = new javax.swing.GroupLayout(btnLogin);
        btnLogin.setLayout(btnLoginLayout);
        btnLoginLayout.setHorizontalGroup(
            btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnLoginLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bt_login)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnLoginLayout.setVerticalGroup(
            btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnLoginLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bt_login)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Login.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 70, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("or");
        Login.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/bgLogin.jpg"))); // NOI18N
        Background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackgroundMouseEntered(evt);
            }
        });
        Login.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Register.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(204, 204, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("REGISTER");
        Register.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setText("Username");
        Register.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 255, 255));
        jLabel9.setText("Phone");
        Register.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 255));
        jLabel10.setText("Email");
        Register.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 255));
        jLabel11.setText("Last Password");
        Register.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 255, 255));
        jLabel12.setText("New Password");
        Register.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        jTextField3.setBackground(new java.awt.Color(0, 0, 0, 50));
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        Register.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 200, -1));

        jTextField4.setBackground(new java.awt.Color(0, 0, 0, 50));
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        Register.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 200, -1));

        jTextField5.setBackground(new java.awt.Color(0, 0, 0, 50));
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        Register.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 200, -1));

        jPasswordField3.setBackground(new java.awt.Color(0, 0, 0, 50));
        jPasswordField3.setForeground(new java.awt.Color(255, 255, 255));
        Register.add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 200, -1));

        jPasswordField4.setBackground(new java.awt.Color(0, 0, 0, 50));
        jPasswordField4.setForeground(new java.awt.Color(255, 255, 255));
        Register.add(jPasswordField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 200, -1));

        haveAccount.setBackground(new java.awt.Color(0, 0, 0));
        haveAccount.setForeground(new java.awt.Color(153, 153, 153));
        haveAccount.setText("Do you Have Account ?");
        haveAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                haveAccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                haveAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                haveAccountMouseExited(evt);
            }
        });
        Register.add(haveAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, -1, 30));

        btnRegCreate.setBackground(new java.awt.Color(153, 153, 153));
        btnRegCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegCreateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegCreateMouseExited(evt);
            }
        });

        jLabel14.setText("Create");

        javax.swing.GroupLayout btnRegCreateLayout = new javax.swing.GroupLayout(btnRegCreate);
        btnRegCreate.setLayout(btnRegCreateLayout);
        btnRegCreateLayout.setHorizontalGroup(
            btnRegCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(btnRegCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnRegCreateLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnRegCreateLayout.setVerticalGroup(
            btnRegCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(btnRegCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnRegCreateLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Register.add(btnRegCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 70, 30));

        jCheckBox1.setBackground(new java.awt.Color(0, 0, 0, 0));
        jCheckBox1.setForeground(new java.awt.Color(204, 255, 255));
        jCheckBox1.setText("I Agree for all services");
        Register.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 200, -1));

        background2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        background2.setForeground(new java.awt.Color(204, 255, 255));
        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/bgLogin.jpg"))); // NOI18N
        Register.add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Menu.setBackground(new java.awt.Color(34, 49, 63));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listMenu.setBackground(new java.awt.Color(52, 73, 94));

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/c.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("ADMIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator1)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnTambahData.setForeground(new java.awt.Color(204, 204, 204));
        btnTambahData.setText("T A M B A H  D A T A");
        btnTambahData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahDataMouseClicked(evt);
            }
        });

        btnJualBarang.setForeground(new java.awt.Color(204, 204, 204));
        btnJualBarang.setText("J U A L  B A R A N G");
        btnJualBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnJualBarangMouseClicked(evt);
            }
        });

        btnCekstok.setForeground(new java.awt.Color(204, 204, 204));
        btnCekstok.setText("C E K  S T O K");
        btnCekstok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCekstokMouseClicked(evt);
            }
        });

        btnAbout.setBackground(new java.awt.Color(204, 204, 204));
        btnAbout.setForeground(new java.awt.Color(204, 204, 204));
        btnAbout.setText("A B O U T");
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutMouseClicked(evt);
            }
        });

        btnLogout.setForeground(new java.awt.Color(204, 204, 204));
        btnLogout.setText("L O G O U T");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });

        btnHistoriPenjualan.setForeground(new java.awt.Color(204, 204, 204));
        btnHistoriPenjualan.setText("  H I S T O R I  ");
        btnHistoriPenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistoriPenjualanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout listMenuLayout = new javax.swing.GroupLayout(listMenu);
        listMenu.setLayout(listMenuLayout);
        listMenuLayout.setHorizontalGroup(
            listMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(listMenuLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnTambahData))
            .addGroup(listMenuLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnJualBarang))
            .addGroup(listMenuLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnLogout))
            .addGroup(listMenuLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(btnAbout))
            .addGroup(listMenuLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(listMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnHistoriPenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCekstok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        listMenuLayout.setVerticalGroup(
            listMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listMenuLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTambahData)
                .addGap(38, 38, 38)
                .addComponent(btnJualBarang)
                .addGap(38, 38, 38)
                .addComponent(btnCekstok)
                .addGap(38, 38, 38)
                .addComponent(btnHistoriPenjualan)
                .addGap(38, 38, 38)
                .addComponent(btnAbout)
                .addGap(79, 79, 79)
                .addComponent(btnLogout))
        );

        Menu.add(listMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        panelWelcome.setBackground(new java.awt.Color(34, 49, 63));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("WELCOME TO THE APP");

        javax.swing.GroupLayout panelWelcomeLayout = new javax.swing.GroupLayout(panelWelcome);
        panelWelcome.setLayout(panelWelcomeLayout);
        panelWelcomeLayout.setHorizontalGroup(
            panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWelcomeLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel16)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        panelWelcomeLayout.setVerticalGroup(
            panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWelcomeLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel16)
                .addContainerGap(467, Short.MAX_VALUE))
        );

        Menu.add(panelWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 620, 550));

        panelTambahData.setBackground(new java.awt.Color(34, 49, 63));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("TAMBAH DATA");

        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Kode");

        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Nama");

        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("Tipe");

        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("Harga");

        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("Jumlah");

        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("Keterangan");

        txtTambahKeterangan.setColumns(20);
        txtTambahKeterangan.setRows(5);
        jScrollPane1.setViewportView(txtTambahKeterangan);

        jLabel24.setText("SIMPAN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 64, Short.MAX_VALUE)
                    .addComponent(jLabel24)
                    .addGap(0, 64, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel24)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelTambahDataLayout = new javax.swing.GroupLayout(panelTambahData);
        panelTambahData.setLayout(panelTambahDataLayout);
        panelTambahDataLayout.setHorizontalGroup(
            panelTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTambahDataLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20)
                    .addComponent(jLabel18)
                    .addComponent(txtTambahKode)
                    .addComponent(jLabel19)
                    .addComponent(txtTambahNamaBarang)
                    .addComponent(txtTambahTipe, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel21)
                        .addComponent(txtTambahHarga)
                        .addComponent(jLabel22)
                        .addComponent(txtTambahJumlah, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                    .addComponent(jLabel23)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
            .addGroup(panelTambahDataLayout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addGroup(panelTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        panelTambahDataLayout.setVerticalGroup(
            panelTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTambahDataLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel17)
                .addGap(36, 36, 36)
                .addGroup(panelTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTambahKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTambahHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(panelTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTambahNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTambahJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(panelTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTambahTipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        Menu.add(panelTambahData, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 620, 550));

        panelJualBarang.setBackground(new java.awt.Color(34, 49, 63));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setText("JUAL BARANG");

        jLabel26.setForeground(new java.awt.Color(204, 204, 204));
        jLabel26.setText("Tanggal");

        jLabel27.setForeground(new java.awt.Color(204, 204, 204));
        jLabel27.setText("Nama Barang");

        jLabel28.setForeground(new java.awt.Color(204, 204, 204));
        jLabel28.setText("Nama Pembeli");

        jLabel29.setForeground(new java.awt.Color(204, 204, 204));
        jLabel29.setText("Tipe");

        jLabel30.setForeground(new java.awt.Color(204, 204, 204));
        jLabel30.setText("Kode");

        jLabel31.setForeground(new java.awt.Color(204, 204, 204));
        jLabel31.setText("Jumlah");

        jLabel32.setText("SIMPAN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 64, Short.MAX_VALUE)
                    .addComponent(jLabel32)
                    .addGap(0, 64, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel32)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelJualBarangLayout = new javax.swing.GroupLayout(panelJualBarang);
        panelJualBarang.setLayout(panelJualBarangLayout);
        panelJualBarangLayout.setHorizontalGroup(
            panelJualBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJualBarangLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel25)
                .addContainerGap(257, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJualBarangLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(panelJualBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel30)
                    .addComponent(jLabel26)
                    .addComponent(jLabel28)
                    .addComponent(txtJualNamaPembeli)
                    .addComponent(txtJualKode, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txtJualTanggal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelJualBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel27)
                    .addComponent(jLabel29)
                    .addComponent(jLabel31)
                    .addComponent(txtJualTipe, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txtJualBarang)
                    .addComponent(txtJualJumlah, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(63, 63, 63))
            .addGroup(panelJualBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelJualBarangLayout.createSequentialGroup()
                    .addGap(227, 227, 227)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(227, Short.MAX_VALUE)))
        );
        panelJualBarangLayout.setVerticalGroup(
            panelJualBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJualBarangLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel25)
                .addGap(43, 43, 43)
                .addGroup(panelJualBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelJualBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJualTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJualBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(panelJualBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelJualBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJualNamaPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJualTipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(panelJualBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelJualBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJualKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJualJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(213, Short.MAX_VALUE))
            .addGroup(panelJualBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelJualBarangLayout.createSequentialGroup()
                    .addContainerGap(440, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(79, 79, 79)))
        );

        Menu.add(panelJualBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 620, 550));

        panelCekStok.setBackground(new java.awt.Color(34, 49, 63));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 204, 204));
        jLabel33.setText("Cek Stok");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel34.setText("SORT");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 19, Short.MAX_VALUE)
                    .addComponent(jLabel34)
                    .addGap(0, 20, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 4, Short.MAX_VALUE)
                    .addComponent(jLabel34)
                    .addGap(0, 4, Short.MAX_VALUE)))
        );

        jLabel35.setText("SEARCH");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 19, Short.MAX_VALUE)
                    .addComponent(jLabel35)
                    .addGap(0, 20, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 3, Short.MAX_VALUE)
                    .addComponent(jLabel35)
                    .addGap(0, 3, Short.MAX_VALUE)))
        );

        jLabel39.setText("EDIT");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 18, Short.MAX_VALUE)
                    .addComponent(jLabel39)
                    .addGap(0, 19, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 4, Short.MAX_VALUE)
                    .addComponent(jLabel39)
                    .addGap(0, 4, Short.MAX_VALUE)))
        );

        jLabel40.setText("HAPUS");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 14, Short.MAX_VALUE)
                    .addComponent(jLabel40)
                    .addGap(0, 13, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 4, Short.MAX_VALUE)
                    .addComponent(jLabel40)
                    .addGap(0, 4, Short.MAX_VALUE)))
        );

        jTable1.setBackground(new java.awt.Color(34, 49, 63));
        jTable1.setForeground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama Barang", "Jenis", "Tipe", "Jumlah", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout panelCekStokLayout = new javax.swing.GroupLayout(panelCekStok);
        panelCekStok.setLayout(panelCekStokLayout);
        panelCekStokLayout.setHorizontalGroup(
            panelCekStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCekStokLayout.createSequentialGroup()
                .addGroup(panelCekStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCekStokLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel33))
                    .addGroup(panelCekStokLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(panelCekStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCekStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(panelCekStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelCekStokLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelCekStokLayout.setVerticalGroup(
            panelCekStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCekStokLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel33)
                .addGap(31, 31, 31)
                .addGroup(panelCekStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCekStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCekStokLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCekStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCekStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField15)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        Menu.add(panelCekStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 620, 550));

        panelHistori.setBackground(new java.awt.Color(34, 49, 63));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(204, 204, 204));
        jLabel36.setText("HISTORI PENJUALAN");

        javax.swing.GroupLayout panelHistoriLayout = new javax.swing.GroupLayout(panelHistori);
        panelHistori.setLayout(panelHistoriLayout);
        panelHistoriLayout.setHorizontalGroup(
            panelHistoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHistoriLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel36)
                .addContainerGap(201, Short.MAX_VALUE))
        );
        panelHistoriLayout.setVerticalGroup(
            panelHistoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHistoriLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel36)
                .addContainerGap(475, Short.MAX_VALUE))
        );

        Menu.add(panelHistori, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 620, 550));

        panelAbout.setBackground(new java.awt.Color(34, 49, 63));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(204, 204, 204));
        jLabel37.setText("ABOUT");

        jLabel38.setText("Dev : ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel38)
                .addContainerGap(504, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel38)
                .addContainerGap(400, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelAboutLayout = new javax.swing.GroupLayout(panelAbout);
        panelAbout.setLayout(panelAboutLayout);
        panelAboutLayout.setHorizontalGroup(
            panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAboutLayout.createSequentialGroup()
                .addGroup(panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAboutLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel37))
                    .addGroup(panelAboutLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        panelAboutLayout.setVerticalGroup(
            panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAboutLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel37)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        Menu.add(panelAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 620, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    Color awalLogReg = new Color(153,153,153);
    Color rubahLogReg = new Color(204,204,204);
    Color haveAcc = new Color(153,153,255);
    
    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
    try {
            sql = "SELECT * FROM admin WHERE username='"+txt_name.getText()+"' AND password='"+txt_pass.getText()+"'";
            rs = stat.executeQuery(sql);
            if(rs.next()){
                if(txt_name.getText().equals(rs.getString("username")) && txt_pass.getText().equals(rs.getString("password"))){
                    JOptionPane.showMessageDialog(null, "berhasil login");
                    
                    listMenu.setVisible(true);
                    Menu.setVisible(true);
                    Register.setVisible(false);
                    Login.setVisible(false);
                    panelWelcome.setVisible(true);
                    panelJualBarang.setVisible(false);
                    panelTambahData.setVisible(false);
                    panelJualBarang.setVisible(false);
                    panelCekStok.setVisible(false);
                    panelHistori.setVisible(false);
                    panelAbout.setVisible(false);
                    
                }
            }else{
                    JOptionPane.showMessageDialog(null, "username atau password salah");
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }    
        
        
        
        
        
        
        //menu mn = new menu();
        //mn.setVisible(true);
        //dispose();
        /*
        listMenu.setVisible(true);
        Menu.setVisible(true);
        Register.setVisible(false);
        Login.setVisible(false);
        panelWelcome.setVisible(true);
        panelJualBarang.setVisible(false);
        panelTambahData.setVisible(false);
        panelJualBarang.setVisible(false);
        panelCekStok.setVisible(false);
        panelHistori.setVisible(false);
        panelAbout.setVisible(false);
        */
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        // TODO add your handling code here:
        btnLogin.setBackground(rubahLogReg);
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        // TODO add your handling code here:
        btnLogin.setBackground(awalLogReg);
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMouseClicked
        // TODO add your handling code here:
        Register.setVisible(true);
        Login.setVisible(false);
        panelWelcome.setVisible(false);
        panelJualBarang.setVisible(false);
        panelTambahData.setVisible(false);
        panelJualBarang.setVisible(false);
        panelCekStok.setVisible(false);
        panelHistori.setVisible(false);
        panelAbout.setVisible(false);
    }//GEN-LAST:event_btnCreateMouseClicked

    private void btnCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMouseEntered
        // TODO add your handling code here:
        btnCreate.setBackground(rubahLogReg);
    }//GEN-LAST:event_btnCreateMouseEntered

    private void btnCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMouseExited
        // TODO add your handling code here:
        btnCreate.setBackground(awalLogReg);
    }//GEN-LAST:event_btnCreateMouseExited

    private void BackgroundMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundMouseEntered
        // TODO add your handling code here:
        btnLogin.setVisible(true);
        Register.setVisible(false);
    }//GEN-LAST:event_BackgroundMouseEntered

    private void haveAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_haveAccountMouseClicked
        // TODO add your handling code here:
        Login.setVisible(true);
        Register.setVisible(false);
    }//GEN-LAST:event_haveAccountMouseClicked

    private void haveAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_haveAccountMouseEntered
        // TODO add your handling code here:
        haveAccount.setForeground(rubahLogReg);
    }//GEN-LAST:event_haveAccountMouseEntered

    private void haveAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_haveAccountMouseExited
        // TODO add your handling code here:
        haveAccount.setForeground(awalLogReg);
    }//GEN-LAST:event_haveAccountMouseExited

    private void txt_passMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_passMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passMouseEntered

    private void txt_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_passMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passMouseClicked

    private void btnRegCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegCreateMouseClicked
        // TODO add your handling code here:
        Register.setVisible(false);
        Login.setVisible(true);
        panelWelcome.setVisible(false);
        panelJualBarang.setVisible(false);
        panelTambahData.setVisible(false);
        panelJualBarang.setVisible(false);
        panelCekStok.setVisible(false);
        panelHistori.setVisible(false);
        panelAbout.setVisible(false);
    }//GEN-LAST:event_btnRegCreateMouseClicked

    private void btnRegCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegCreateMouseEntered
        // TODO add your handling code here:
        btnRegCreate.setBackground(rubahLogReg);
    }//GEN-LAST:event_btnRegCreateMouseEntered

    private void btnRegCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegCreateMouseExited
        // TODO add your handling code here:
        btnRegCreate.setBackground(awalLogReg);
    }//GEN-LAST:event_btnRegCreateMouseExited

    private void btnTambahDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahDataMouseClicked
        // TODO add your handling code here:
        panelWelcome.setVisible(false);
        panelTambahData.setVisible(true);
        panelJualBarang.setVisible(false);
        panelCekStok.setVisible(false);
        panelHistori.setVisible(false);
        panelAbout.setVisible(false);
    }//GEN-LAST:event_btnTambahDataMouseClicked

    private void btnJualBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJualBarangMouseClicked
        // TODO add your handling code here:
        panelWelcome.setVisible(false);
        panelTambahData.setVisible(false);
        panelJualBarang.setVisible(true);
        panelCekStok.setVisible(false);
        panelHistori.setVisible(false);
        panelAbout.setVisible(false);
    }//GEN-LAST:event_btnJualBarangMouseClicked

    private void btnCekstokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCekstokMouseClicked
        // TODO add your handling code here:
        panelWelcome.setVisible(false);
        panelTambahData.setVisible(false);
        panelJualBarang.setVisible(false);
        panelCekStok.setVisible(true);
        panelHistori.setVisible(false);
        panelAbout.setVisible(false);
    }//GEN-LAST:event_btnCekstokMouseClicked

    private void btnAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseClicked
        // TODO add your handling code here:
        panelWelcome.setVisible(false);
        panelTambahData.setVisible(false);
        panelJualBarang.setVisible(false);
        panelCekStok.setVisible(false);
        panelHistori.setVisible(false);
        panelAbout.setVisible(true);
    }//GEN-LAST:event_btnAboutMouseClicked

    private void btnHistoriPenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistoriPenjualanMouseClicked
        // TODO add your handling code here:
        panelWelcome.setVisible(false);
        panelTambahData.setVisible(false);
        panelJualBarang.setVisible(false);
        panelCekStok.setVisible(false);
        panelHistori.setVisible(true);
        panelAbout.setVisible(false);
    }//GEN-LAST:event_btnHistoriPenjualanMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        Register.setVisible(false);
        Login.setVisible(true);
        panelWelcome.setVisible(false);
        panelJualBarang.setVisible(false);
        panelTambahData.setVisible(false);
        panelJualBarang.setVisible(false);
        panelCekStok.setVisible(false);
        panelHistori.setVisible(false);
        panelAbout.setVisible(false);
    }//GEN-LAST:event_btnLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Register;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel bt_login;
    private javax.swing.JLabel btnAbout;
    private javax.swing.JLabel btnCekstok;
    private javax.swing.JPanel btnCreate;
    private javax.swing.JLabel btnHistoriPenjualan;
    private javax.swing.JLabel btnJualBarang;
    private javax.swing.JPanel btnLogin;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JPanel btnRegCreate;
    private javax.swing.JLabel btnTambahData;
    private javax.swing.JLabel haveAccount;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPanel listMenu;
    private javax.swing.JPanel panelAbout;
    private javax.swing.JPanel panelCekStok;
    private javax.swing.JPanel panelHistori;
    private javax.swing.JPanel panelJualBarang;
    private javax.swing.JPanel panelTambahData;
    private javax.swing.JPanel panelWelcome;
    private javax.swing.JTextField txtJualBarang;
    private javax.swing.JTextField txtJualJumlah;
    private javax.swing.JTextField txtJualKode;
    private javax.swing.JTextField txtJualNamaPembeli;
    private javax.swing.JTextField txtJualTanggal;
    private javax.swing.JTextField txtJualTipe;
    private javax.swing.JTextField txtTambahHarga;
    private javax.swing.JTextField txtTambahJumlah;
    private javax.swing.JTextArea txtTambahKeterangan;
    private javax.swing.JTextField txtTambahKode;
    private javax.swing.JTextField txtTambahNamaBarang;
    private javax.swing.JTextField txtTambahTipe;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_pass;
    // End of variables declaration//GEN-END:variables
}
